### ISSUE TITLE
umask leaks from host to stacker environment

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#303]
The umask of the calling process leaks into the stacker build environment.
Here is an example, stacker version here is:
    stacker version stacker v0.17.0 liblxc 7e37cc96bb94175a8e351025d26cc35dc2d10543

Here is my stacker.yaml
```yaml
$ cat stacker.yaml
build:
  build_only: true
  from:
    type: docker
    url: "${{IMAGE_URL:-docker://alpine:edge}}"
  build_only: true
  run: |
    rm -f testme
    umask
    touch testme
    ls -l testme
```

Build as as root, umask is 0022 resulting in 644 perms for file:
```bash
$ sudo id
uid=0(root) gid=0(root) groups=0(root),130(sbuild)

$ sudo bash -c 'umask'
0022

$ sudo stacker clean
using storage backend overlay

$ sudo stacker build --substitute=IMAGE_URL=docker://aci-zot.cisco.com:5050/alpine:edge
using storage backend overlay
preparing image build...
loading docker://aci-zot.cisco.com:5050/alpine:edge
Copying blob 41dcc117e123 done  
Copying config deb7de34b9 done  
Writing manifest to image destination
Storing signatures
+ rm -f testme
+ umask
0022
+ touch testme
+ ls -l testme
-rw-r--r--    1 root     root             0 Aug  9 02:18 testme
```

Build as unpriv user, umask is 0002 resulting in 664 perms for file.
```bash
$ id -u
1000

$ bash -c 'umask'
0002

$ stacker build --substitute=IMAGE_URL=docker://aci-zot.cisco.com:5050/alpine:edge
using storage backend overlay
preparing image build...
loading docker://aci-zot.cisco.com:5050/alpine:edge
Copying blob 41dcc117e123 done  
Copying config deb7de34b9 done  
Writing manifest to image destination
Storing signatures
+ rm -f testme
+ umask
0002
+ touch testme
+ ls -l testme
-rw-rw-r--    1 root     root             0 Aug  9 02:20 testme
```
