### ISSUE TITLE
Using substitution for long strings on multiple lines breaks yaml spec

### ISSUE THREAD

**Issue by peusebiu** [project-stacker/stacker#313]
Using this stacker.yaml spec:
```
${{IMAGE_NAME}}:
  from:
    type: docker
    url: docker://${{IMAGE_NAME}}:${{IMAGE_TAG}}
  annotations:
    org.opencontainers.image.documentation: ${{DOCUMENTATION}}
```

If I try to substitute DOCUMENTATION with the contents of a file having multiple lines it will break yaml spec.

Repro steps:

1. having the above stacker yaml
2. create a new file with more than one line
```
peusebiu@PEUSEBIU-FC130:~/repro_stacker$ cat doc.md 
line


newline



more newlines
```
3. doc=$(cat doc.md)
4. sudo stacker --debug build -f stacker.yaml --substitute IMAGE_NAME=busybox --substitute IMAGE_TAG=latest --substitute DOCUMENTATION="$doc"

```
peusebiu@PEUSEBIU-FC130:~/repro_stacker$ sudo stacker --debug build -f stacker.yaml --substitute IMAGE_NAME=busybox --substitute IMAGE_TAG=latest --substitute DOCUMENTATION="$doc"
stacker version c0962f8cd9c0c4a704fb7aa652368d0f24d6457f
No uid mappings, running as root
stacker version c0962f8cd9c0c4a704fb7aa652368d0f24d6457f
initializing stacker recipe: stacker.yaml
substituting $IMAGE_NAME to busybox
substituting $IMAGE_TAG to latest
substituting $DOCUMENTATION to line


newline



more newlines
substituting $STACKER_ROOTFS_DIR to /home/peusebiu/repro_stacker/roots
substituting $STACKER_STACKER_DIR to /home/peusebiu/repro_stacker/.stacker
substituting $STACKER_OCI_DIR to /home/peusebiu/repro_stacker/oci
error: yaml: line 13: could not find expected ':'
couldn't parse stacker file stacker.yaml
```
