### ISSUE TITLE
feature request: `stacker watchme`

### ISSUE THREAD

**Issue by mikemccracken** [project-stacker/stacker#316]
Maybe this needs a better name but here's the idea:

```
% ls
mybinary
myconfig.conf
myservice.service
% stacker watchme myimagename --from mybaseimageurl
downloading mybaseimageurl
starting /bin/bash in container
/stacker > cp mybinary /usr/bin/
/stacker > cp myconfig.conf /var/lib/mybinary/
/stacker > cp myservice.service /etc/systemd/system/
/stacker > systemctl enable myservice
/stacker > stacker-set full_command mybinary --args=blarg
/stacker > exit
writing to stacker.yaml
```

creates this stacker file:

```yaml
myimagename:
  from:
    type: docker
    url: myimageurl
  import:
    - {path: mybinary, hash: cafebeef}
    - {path: myconfig.conf, hash: beefcafe}
    - {path: myservice.service, hash: beefbeef}
  run:
    - cp /stacker/mybinary /usr/bin
    - cp /stacker/myconfig.conf /var/lib/mybinary/
    - cp /stacker/myservice.service /etc/systemd/system/
    - systemctl enable myservice
  full_command: mybinary --args blarg
```

you could also imagine stacker watchme on an existing stackerfile that just runs the current file and drops into this recorded shell after the last thing runs, to append to / update the file
