### ISSUE TITLE
Unable to use squashfs without tar layers

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#319]
I'm trying to use only squashfs layers, and running into a problem that occurs both as unprivileged and privileged user.

Basically trying to build this stacker.yaml with only `--layer-type=squashfs`
```yaml
rootfs:
  from:
    type: docker
    url: "${{BASE_URL}}${{LAYER_SUFFIX}}"
  import:
    - hello-world
  run: |
    cp /stacker/hello-world /usr/bin/
    chmod 755 /usr/bin/hello-world
    /usr/bin/hello-world
```

This can be reproduced with [go-test.sh](https://github.com/project-stacker/stacker/files/9842697/go-test.sh.txt) as root or non-root.  Just point it at a url that has both -squashfs and tar formats.  Both root and non-root paths fail.

Output of go-test.sh is attached:
 * as root : [root.log](https://github.com/project-stacker/stacker/files/9842702/root.log)
 * as non-root [no-root.log](https://github.com/project-stacker/stacker/files/9842700/no-root.log)
