### ISSUE TITLE
Bug: top level directories are removed if there is only one

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#370]
### stacker version

v0.30.1-15-gdc0ada0

### Describe the bug

If you attempt to build the stacker.yaml below it will fail.
The reason is that the `/files` directory is stripped away in the 'mybuild'  layer.  The files 'subuid' and 'subgid' are directly in /.

    $ stacker build --layer-type=squashfs --layer-type=tar
    ...
    error: lstat /files/subuid: no such file or directory
    error: execute failed: exit status 1
    error: exit status 1

```yaml
$ cat stacker.yaml 
mybuild:
  from:
    type: scratch
  import:
    - path: /etc/subuid
      dest: /files/
    - path: /etc/subgid
      dest: /files

mytest:
  from: 
    type: docker
    url: docker://ubuntu:latest
  import:
    - stacker://mybuild/files/subuid
    - stacker://mybuild/files/subgid
  run: |
    ls -l /stacker
```

**Comment by smoser** [comment]
Part of the fix is this:
```
--- a/pkg/squashfs/squashfs.go
+++ b/pkg/squashfs/squashfs.go
@@ -135,7 +135,7 @@ func MakeSquashfs(tempdir string, rootfs string, eps *ExcludePaths, verity Verit
        tmpSquashfs.Close()
        os.Remove(tmpSquashfs.Name())
        defer os.Remove(tmpSquashfs.Name())
-       args := []string{rootfs, tmpSquashfs.Name()}
+       args := []string{rootfs, tmpSquashfs.Name(), "-keep-as-directory"}
        compression := GzipCompression
        if mksquashfsSupportsZstd() {
                args = append(args, "-comp", "zstd")
```

but I think the problem is also happening with tar layers. (fails to build with '--layer-type=tar' also).

**Comment by smoser** [comment]
When I was poking around trying to fix this, I noticed that each 'import' gets creates its own layer in the created oci. 
i think it might be better to have stacker start populating the same overlay that the 'run' would be handed before 'run' (if present) occurs.

Given this stcker.lyaml:
```yaml
mybuild:
  from:
    type: docker
    url: ubuntu:latest
  import:
    - my-file
    - path: /etc/passwd
      dest: /etc/passwd-host
    - path: /static/some-binary-here
      dest: /usr/bin/
  run: |
    ls -l /usr/bin/some-binary-here
    ls -l /etc/passwd /etc/passwd-host
    ls -l /stacker/my-file
```

When 'run' occurred:
 * there would be read-only bind-mount on /stacker (current behavior, i think)
 * / would be a single overlay as if imports[1] and imports[2] were not present.
 * /usr/bin/some-binary-here would be present.

I know that @rchincha was interested in keeping the import logic as simple as possible, and for sure we have some corner cases to work out with the above. What I suggest to handle those edge cases (new file over existing directory, symlink following ...) is just to mimic what gnu 'tar' would do. And one path we could follow for implementation would be to have all the 'import' statements ultimately result in a tar archive, and then to just enter the filesystem view (including /overlay) and extract that tar archive .
