### ISSUE TITLE
Feat: add SBOM support

### ISSUE THREAD

**Issue by rchincha** [project-stacker/stacker#374]
### Is your feature request related to a problem? Please describe.

Generate SBOMs of out generated layers.

**Comment by rchincha** [comment]
Add a directive as follows:

```
build:
  from: ...
  bom:
      - package: pkg1
         path: /dir1
      - package: pkg2
         path: /dir2
    run: |
         my-bom-tool ... > /stacker-artifacts/test.bom
   ...
```

When the `bom` directive is specified, a /stacker-artifacts is also bind-mounted into the container
One can run their own bom tool to genetate BOMs etc and output under /stacker-artifacts. We do this since it is not realistically possible to enable all scenarios (pkg mgmt cleanup, build/pkging staging, etc)
One can also just specific bom generation directives.
Each layer also gets a full file list of paths, sizes and checksums.
This list is compared with the generated boms and if there are missing files, then the build fails - we must account for **everything**.

In terms of implementation, we create a `internal-go bom` cmd for the `bom:` directive. This must run in the container with the layer rootfs.
