### ISSUE TITLE
Bug: overlay,userxattr directory created in roots/<layer>/ during squashfs biulds

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#388]
### stacker version

v0.40.1-e54a685

### Describe the bug

```
$ stacker build
preparing image minbase...
loading docker://alpine:edge
Copying blob a71ff8a5264a done  
Copying config 09b6b3579b done  
Writing manifest to image destination
Storing signatures
+ echo all done.
all done.

$ ls -l roots/minbase/
total 24
drwxr-xr-x 3 smoser smoser 4096 Jan 10 09:07 overlay
-rw-r--r-- 1 smoser smoser  458 Jan 10 09:07 overlay_metadata.json
drwxr-xr-x 2 smoser smoser 4096 Jan 10 09:07 overlay,userxattr
drwxr-xr-x 2 smoser smoser 4096 Jan 10 09:07 rootfs
drwxr-xr-x 3 smoser smoser 4096 Jan 10 09:07 work
drwxr-xr-x 2 smoser smoser 4096 Jan 10 09:07 workaround0
```

The 'overlay' dir is probably not necessary to be there (stacker could just create a tmpdir always on mount), but the 'overlay,usrexattr' dir is I think fallout of `GetLXCRootfsConfig` in `pkg/overlay/overlay.go` doing :

```golang
    return fmt.Sprintf("overlay:%s,userxattr", lxcRootfsString), nil 
```

I think that lxc is not understanding the intent of userxattr there.

See stacker.yaml below.

```yaml
$ cat stacker.yaml 
minbase:
  build_only: true
  from:
    type: docker
    url: ${{DOCKER_BASE:docker://}}alpine:edge
  run: |
    echo all done.
```
