### ISSUE TITLE
Bug: `stacker build` should error when importing from a bind mount that will not be present

### ISSUE THREAD

**Issue by mikemccracken** [project-stacker/stacker#449]
### stacker version

v0.40.1

### Describe the bug

this file sets up one build layer that bind mounts the current dir, then writes a file there.
then in a second container it imports that directory. the import does not fail, it just creates an empty directory because mounts are not in the stacker cache.
this should fail to build, as there is no good reason to want that behavior and it is definitely a misunderstanding of binds.
the error message should explain that you need to copy out of the bind in order to share results.

the third container is an example of where we do error if we would be importing a nonexistent dir. this is good and we should do it this way consistently

```yaml
A:
  from:
    type: docker
    url: ${{C3_REGISTRY}}/minbase:${{C3_VERSION}}
  binds:
    - . -> /root/bind-A
  build_only: true
  run: |
    cd /root/bind-A
    touch A_WAS_HERE


B:
  from:
    type: docker
    url: ${{C3_REGISTRY}}/minbase:${{C3_VERSION}}
  import:
    - stacker://A/root/bind-A
  run: |
    cd /stacker/bind-A
    ls -la

C:
  from:
    type: docker
    url: ${{C3_REGISTRY}}/minbase:${{C3_VERSION}}
  import:
    - stacker://A/root/this/does/not/exist
  run: |
    cd /stacker/
    ls -la
```

output from building this

```
preparing image A...
loading docker://aci-zot.cisco.com:5000/c3/minbase:1.0.45
Copying blob 437ed04833c4 done
Copying blob 5e9a280e11ef done
Copying config c9bcd94174 done
Writing manifest to image destination
Storing signatures
+ cd /root/bind-A
+ touch A_WAS_HERE
preparing image B...
loading docker://aci-zot.cisco.com:5000/c3/minbase:1.0.45
Copying blob 437ed04833c4 skipped: already exists
Copying blob 5e9a280e11ef skipped: already exists
Copying config c9bcd94174 done
Writing manifest to image destination
Storing signatures
+ cd /stacker/bind-A
+ ls -la
total 8
drwxr-xr-x 2 root root 4096 Mar 30 19:30 .
drwxr-xr-x 3 root root 4096 Mar 30 19:30 ..
filesystem B built successfully
preparing image C...
error: lstat /root/this/does/not/exist: no such file or directory
error: execute failed: exit status 1
error: exit status 1
make: *** [Makefile:21: repro] Error 1
```

### To reproduce

run stacker build on that yaml, use appropriate substitutions for the registry/tag subs

### Expected behavior

image `B` should fail to build with a helpful error like "importing from bind mounted directories is not supported, copy files out of the bind in the original container or re-do the bind in the child container"
