### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by andaaron** [project-stacker/stacker#451]
### stacker version

v1.0.0-rc4-8e267fc

### Describe the bug

We need a way to import the content of a folder at destination, without creating a folder with the source root folder name at destination.

### To reproduce

```
stacker --version
stacker version stacker v1.0.0-rc4-8e267fc liblxc 727adc05220e9b8b594c5bc2124bef5b2e0abe7a
```

There is no way to import the content of a folder into a layer without stacker creating the folder itself in the new image.

Given
```
tree folder1
folder1
├── file1
└── file2
```

and

```
layer1:
  from:
    type: docker
    url: docker://ubuntu:latest
  import:
    - path: folder1/
      dest: /
  run: |
    ls /
```

the output if stacker build is:

```
preparing image layer1...
loading docker://ubuntu:latest
Copying blob 2ab09b027e7f done
Copying config 08d22c0ceb done
Writing manifest to image destination
Storing signatures
overlay dest / is a symlink, patching to
+ ls /
bin
boot
dev
etc
folder1
home
lib
lib32
lib64
libx32
media
mnt
opt
proc
root
run
sbin
srv
stacker
sys
tmp
usr
var
filesystem layer1 built successfully
```

I need a way to place `file1` and `file2` directly under `/`, not inside `/folder1`.

This issue also reproduces with `stacker://` paths. See below.

```
layer1:
  from:
    type: docker
    url: docker://ubuntu:latest
  run: |
    mkdir /folder1
    touch /folder1/file1
    touch /folder1/file2

layer2:
  from:
    type: docker
    url: docker://ubuntu:latest
  import:
    - path: stacker://layer1/folder1/
      dest: /
  run: |
    ls /
```

### Additional context

This issue is important in the case where the layer where the files are imported does not have a shell, and the import destination cannot be changed (for example scratch layers).

I am especially interested in the import using `stacker://` case
