### ISSUE TITLE
Feat: dynamic annotations

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#477]
### Is your feature request related to a problem? Please describe.

I would like to add information to a stacker built image about its contents.  Annotations seem like the right place to do this.
Specifically, i would like to add an annotation 'dpkg-manifest' with the output of 'dpkg-query --show' so that something can see that information in an image repository.

### Describe the solution you'd like

It seems like `generate_labels` is very similar, but controls oci labels (in a config) section.

I think we could very easily add 'generate_annotations' with the same basic manner:

```yaml
label:
  from:
    type: docker
    url: docker://ubuntu:latest
  run: |
    echo hi mom
  generate_annotations: |
    dpkg-query --show > /oci-annotations/com.example.dpkg_manifest
```
