### ISSUE TITLE
Feat: Allow user to specify a 'dest' to /stacker/imports

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#508]
### Is your feature request related to a problem? Please describe.

I'd like to be able to specify a 'dest' for a import that goes into /stacker/imports.
I think this is a significant shortcoming that should be addressed.  The workaround is for the user to specify a different path (not under /stacker, say '/imports'), but that results in 
a. having to consistently use that 'import' directory
b. having to clean up the import directory so it doesn't appear in the target.

Here is an example stacker.yaml 
```
build:
  build_only: true
  from:
    type: docker
    url: ${{DOCKER_BASE-docker://}busybox:latest
  import:
    - path: bar
      dest: bar.txt
    - path: foo
      dest: /stacker/imports/foo.txt
  run: |
    ls -l /stacker/imports/foo.txt /stacker/improts/bar.txt
```

Neither of the attempts above work with stacker version v1.0.0-rc5-396ff9d.

The first, using a relative path (bar), will complain:

    `error: Dest path cannot be relative for: map[interface {}]interface {}{"dest":"bar.txt", "path":"bar"}`

The second, using an absolute path but explicitly under /stacker/imports (foo), ends up populating an overlay that goes below /stacker/imports, so the 'run' section does not actually see it.

Here is an example script that i'd like to pass.
[test-case.sh.txt](https://github.com/project-stacker/stacker/files/12686753/test-case.sh.txt)
