### ISSUE TITLE
Bug: No caching of import if dest is provided

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#516]
### stacker version

v1.0.0-rc5-396ff9d

### Describe the bug

Stacker does not cache any import items if a 'dest' is provided.

See example 'testme.sh'(https://github.com/project-stacker/stacker/files/12766496/testme.sh.txt) script here.

When executed, it will build a simple stacker.yaml file with 
```
  import:
    - path: https://github.com/cirros-dev/cirros/releases/download/0.6.2/cirros-0.6.2-source.tar.gz
      hash: 1bdd062118722501ed37234729d9164533da6bc3685f162c33924e64e36883b5
      dest: /imports/my.tar.gz
```

After doing so, it will look in the log for 'downloading'.  The idea is that the downloading of the url should only happen once.
That is true if you do not provide a 'dest' argument.  But if dest is provided then the url will be downloaded every time.
