### ISSUE TITLE
Bug: stacker does not notice import file changed

### ISSUE THREAD

**Issue by smoser** [project-stacker/stacker#530]
### stacker version

v1.0.0-rc5-396ff9d liblxc cb8e38aca27a23964941f0f011a8919aab8bebab

### Describe the bug

When using import with a destination, stacker does not realize that a imported file has changed and re-build the content.

```yaml
demo:
  from:
    type: docker
    url: ${{IMAGE:docker://busybox:latest}}
  import:
    - path: import1.txt
      dest: /imports/
  run: |
    #!/bin/sh -e
    read line < /imports/import1.txt
    echo "read $line"
```

Given the above stacker.yaml, run `stacker build` once, change the content of 'import1.txt' and then run it again.  Expectation is that the build would be redone.

### To reproduce

I am attaching a script to automate the testing.
[stacker-test.sh.txt](https://github.com/project-stacker/stacker/files/13168917/stacker-test.sh.txt)

### Expected behavior

Build should occur a second time, after import1.txt content is changed and log shoudl contain output showing that it built.
