### ISSUE TITLE
Feat: support git clone for imports

### ISSUE THREAD

**Issue by mikemccracken** [project-stacker/stacker#630]
### Is your feature request related to a problem? Please describe.

for build containers, it is common to have the run script clone some git repo, sometimes from an external source.
Usually this is followed by checking out a specific commit or tag, to avoid having things change out form under your builds.

It might be a good idea to also check the hash of the resulting HEAD commit against what is expected, to avoid cases where tags move due to mistakes or malice.

### Describe the solution you'd like

This can be done in the script easily enough, but it might be nice to provide this in stacker itself with something like this:

```yaml
imports:
  - repo: https://github.com/left-pad/left-pad
    tag: 1.0-rc12-not-owned
    commit: d3adb33f
```

of course you only really need the commit, but the tag is useful for documentation 

this would result in a clone at `/stacker/imports/left-pad` at the beginning of the run script.
